[package]
name = "linux_vm_manager"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.94"
rsbinder = { version = "0.10", features = ["tokio", "async", "rpc-vsock", "android_16_plus"] }
env_logger = "0.11.5"
forwarder_guest_launcher = { path = "../forwarder_guest_launcher" }
forwarder = { path = "../../libs/libforwarder" }
log = "0.4.22"
shutdown_runner = { path = "../shutdown_runner" }
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
vsock = "0.5.1"
async-trait = "0.1"

[build-dependencies]
rsbinder-aidl = { version = "0.10", features = ["async"] }

[package.metadata.deb]
maintainer = "ferrochrome-dev@google.com"
copyright = "2024, The Android Open Source Project"
depends = "$auto"
maintainer-scripts = "debian/"
systemd-units = { }
